ファイル_CLASSES_X_NAME = "Dan"
ファイル_CLASSES_X_AGE = "14"
ファイル_ERROR = "There is an error!"
ファイル_NO_ERROR = "There is no error!"
ファイル_ERROR_PRINT = "Candice"
ファイル_FINALLY = "Error block finished"
ファイル_INPUT_EX = "Input Example:"
ファイル_INPUT = "Input: "
ファイル_FINDALL_TXT = "Hanime, Hen, Hanime, Hanime"
ファイル_FINDALL = "an"
ファイル_SEARCH_TXT = "Yandere gf punish makes me happy"
ファイル_SEARCH = "\s"
ファイル_SEARCH_PRINT = "First space character located at"
ファイル_SPLIT_TXT = "Hanimes with reverse r is good"
ファイル_SPLIT = "\s"
ファイル_SUB_TXT = "Hanimes with reverse r is good"
ファイル_SUB_SEARCH = "\s"
ファイル_SUB = "ugh"
ファイル_ABS = -8.71
ファイル_CEIL = 1.7
ファイル_FLOOR = 1.8
ファイル_MIN_MAX = 7, 78, 80
ファイル_SQRT = 49